module ReviewConfig exposing (config)

{-| Configuration for `elm-review` (run it with `npx elm-review`, or
`npx elm-review --fix-all` to have it apply the fixes it is sure about).

The rules are deliberately limited to dead code and mechanical
simplifications: things where the fix is obvious and there is no judgement
call to make. Style rules (`NoMissingTypeAnnotation` and friends) are left
out on purpose; adding them is a separate clean-up project, not a lint
setting.

-}

import NoUnused.CustomTypeConstructorArgs
import NoUnused.CustomTypeConstructors
import NoUnused.Dependencies
import NoUnused.Exports
import NoUnused.Modules
import NoUnused.Patterns
import NoUnused.Variables
import Review.Rule as Rule exposing (Rule)
import Simplify


config : List Rule
config =
    [ NoUnused.CustomTypeConstructors.rule []
    , NoUnused.CustomTypeConstructorArgs.rule
    , NoUnused.Dependencies.rule
    , NoUnused.Exports.rule
    , NoUnused.Modules.rule

    -- NoUnused.Parameters is deliberately absent. Nearly every page module
    -- implements callbacks whose shape elm-pages dictates (`view maybeUrl
    -- sharedModel model static`, `head static`, `init flags navigationKey
    -- maybePagePath`), and most of them legitimately ignore some arguments.
    -- The rule reported 55 of those and nothing else; replacing the names
    -- with `_` would only make the signatures harder to read.
    , NoUnused.Patterns.rule
    , NoUnused.Variables.rule
    , Simplify.rule Simplify.defaults
    ]
        |> List.map
            (Rule.ignoreErrorsForDirectories
                -- Generated by elm-pages on every build. It still has to be
                -- *read*, or the page modules would look unused: `page`,
                -- `Data`, `Model` and `Msg` are only referenced from the
                -- generated Main.elm.
                [ ".elm-pages" ]
            )
